volumes:
  postgres-data:

services:

  postgres:
    image: postgres
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat

    ports:
      - '5005:5432'

    expose:
      - '5432'

  chat-api:
    image: chat/api

    build:
      context: ./api
      dockerfile: Dockerfile

    command: bash -c "forever --watch src/index.js"

    environment:
      - POSTGRES_CONNECTION_URI=postgres://postgres:password@postgres:5432/chat

    ports:
      - '5006:3000'

    depends_on:
      postgres:
        condition: service_healthy  # Wait for the postgres container to be healthy
        restart: true

  chat-client:
    image: chat/client

    build:
      context: ./client
      dockerfile: Dockerfile

    command: node server.js

    ports:
      - '5008:8080'
